---
spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev #开发模式
  application:
     name: deptspringcloud-config-spring-dev

---
spring:
  profiles: test
    active:
    - test

---
spring:
  profiles: test #测试模式
  application:
     name: deptspringcloud-config-spring-test
